proxy:
  command: ./node_modules/.bin/coffee ./src/server/index.coffee
  build: ./derby-notebook
  restart: always
  links:
    - redis
    - mongo
    - ipython
  environment:
    HTTP_PORT: "9999"
    IPYTHON_PASSWORD: ""
  ports:
    - "9999:9999"
  volumes:
    - ./derby-notebook/src:/srv/derby-notebook/src
    - ./derby-notebook/public:/srv/derby-notebook/public

redis:
  image: redis

mongo:
  image: dockerfile/mongodb

ipython:
  command: /notebook.sh
  image: ipython/notebook
  ports:
    - "8888:8888"
  environment:
    USE_HTTP: 1
    PASSWORD: ""
  volumes:
    - ./notebooks:/notebooks
